//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientToSelfHost.Duplex {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageDto", Namespace="http://schemas.datacontract.org/2004/07/ChattyDomain")]
    [System.SerializableAttribute()]
    public partial class MessageDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SentAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SentAt {
            get {
                return this.SentAtField;
            }
            set {
                if ((this.SentAtField.Equals(value) != true)) {
                    this.SentAtField = value;
                    this.RaisePropertyChanged("SentAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Duplex.IDuplexMessageService", CallbackContract=typeof(ClientToSelfHost.Duplex.IDuplexMessageServiceCallback))]
    public interface IDuplexMessageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDuplexMessageService/SendMessage", ReplyAction="http://tempuri.org/IDuplexMessageService/SendMessageResponse")]
        void SendMessage(ClientToSelfHost.Duplex.MessageDto message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDuplexMessageService/SendMessage", ReplyAction="http://tempuri.org/IDuplexMessageService/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(ClientToSelfHost.Duplex.MessageDto message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDuplexMessageService/LogMessage")]
        void LogMessage(ClientToSelfHost.Duplex.MessageDto message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDuplexMessageService/LogMessage")]
        System.Threading.Tasks.Task LogMessageAsync(ClientToSelfHost.Duplex.MessageDto message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDuplexMessageService/GetAll", ReplyAction="http://tempuri.org/IDuplexMessageService/GetAllResponse")]
        ClientToSelfHost.Duplex.MessageDto[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDuplexMessageService/GetAll", ReplyAction="http://tempuri.org/IDuplexMessageService/GetAllResponse")]
        System.Threading.Tasks.Task<ClientToSelfHost.Duplex.MessageDto[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDuplexMessageServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDuplexMessageService/NotifyMessage", ReplyAction="http://tempuri.org/IDuplexMessageService/NotifyMessageResponse")]
        void NotifyMessage(ClientToSelfHost.Duplex.MessageDto message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDuplexMessageServiceChannel : ClientToSelfHost.Duplex.IDuplexMessageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DuplexMessageServiceClient : System.ServiceModel.DuplexClientBase<ClientToSelfHost.Duplex.IDuplexMessageService>, ClientToSelfHost.Duplex.IDuplexMessageService {
        
        public DuplexMessageServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public DuplexMessageServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public DuplexMessageServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DuplexMessageServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DuplexMessageServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SendMessage(ClientToSelfHost.Duplex.MessageDto message) {
            base.Channel.SendMessage(message);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(ClientToSelfHost.Duplex.MessageDto message) {
            return base.Channel.SendMessageAsync(message);
        }
        
        public void LogMessage(ClientToSelfHost.Duplex.MessageDto message) {
            base.Channel.LogMessage(message);
        }
        
        public System.Threading.Tasks.Task LogMessageAsync(ClientToSelfHost.Duplex.MessageDto message) {
            return base.Channel.LogMessageAsync(message);
        }
        
        public ClientToSelfHost.Duplex.MessageDto[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ClientToSelfHost.Duplex.MessageDto[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
